[database]
username = "postgres"
password = "postgres"
host = "localhost"
port = 6432
database = "postgres"
migrations = "db/migrations"
timeout = "1s"
max_connections = 0

[server]
static_dir = "assets"

[metrics]
enabled = true

[openapi]
enabled = true

[logging.opentelemetry]
enabled = true
