[database]
username = "postgres"
password = "postgres"
host = "localhost"
port = 5432
database = "postgres"
migrations = "db/migrations"
timeout = "5s"
max_connections = 100

[server]
static_dir = "assets"

[metrics]
enabled = true

[openapi]
enabled = true

[logging.opentelemetry]
enabled = true

[logging.opentelemetry.batch]
scheduled_delay = "500ms"
max_concurrent_exports = 2
max_queue_size = 8192
