[database]
username = "postgres"
password = "postgres"
host = "localhost"
port = 5432
database = "postgres"
migrations = "db/migrations"
timeout = "5s"
max_connections = 100

[server]
static_dir = "assets"

[metrics]
enabled = true

[openapi]
enabled = true

[logging.opentelemetry]
enabled = true
sample_rate = 1

[logging.opentelemetry.batch]
scheduled_delay = "500ms"
max_concurrent_exports = 2
max_queue_size = 8192

[auth]
jwt_encoding_secret = "jwt-secret"
jwt_decoding_secret = "jwt-secret"
