services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    build: ./nsuns-server
    environment:
      DATABASE_HOST: postgres

volumes:
  pgdata:
