[package]
name = "nsuns-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.71"
axum = "0.6.18"
config = "0.13.3"
serde = { version = "1.0.171", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "any", "postgres", "uuid"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util", "timeout"] }
tower-http = { version = "0.4.1", features = ["add-extension", "trace", "cors", "fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
axum-macros = "0.3.7"
serde_json = "1.0.103"
