services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit $?"]
      interval: 1s
      timeout: 1s
      retries: 3

  nsuns:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bookworm-slim
        RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
        COPY . .

        CMD ["./nsuns-server"]
    ports:
      - '80:8080'
    environment:
      - DATABASE_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
