import { NewProgramTemplate } from "../programTemplate";

export default {
  name: "NSuns 5-Day",
  days: [
    {
      sets: [],
    },
    {
      sets: [
        {
          amount: 65,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 80,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 65,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 8,
          repsIsMinimum: true,
        },
        {
          amount: 50,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 0,
          description: "Chest, Arms, Back",
          movementIndex: 6,
          percentageOfMaxIndex: null,
          reps: null,
          repsIsMinimum: false,
        },
      ],
    },
    {
      sets: [
        {
          amount: 75,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 95,
          description: "Peak set",
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 1,
          repsIsMinimum: true,
        },
        {
          amount: 90,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 80,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 65,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: true,
        },
        {
          amount: 50,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 4,
          percentageOfMaxIndex: 3,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 0,
          description: "Legs, Abs",
          movementIndex: 6,
          percentageOfMaxIndex: null,
          reps: null,
          repsIsMinimum: false,
        },
      ],
    },
    {
      sets: [
        {
          amount: 75,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 95,
          description: "Peak set",
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 1,
          repsIsMinimum: true,
        },
        {
          amount: 90,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 80,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 65,
          description: null,
          movementIndex: 2,
          percentageOfMaxIndex: 2,
          reps: 5,
          repsIsMinimum: true,
        },
        {
          amount: 50,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 0,
          description: "Shoulders, Chest",
          movementIndex: 6,
          percentageOfMaxIndex: null,
          reps: null,
          repsIsMinimum: false,
        },
      ],
    },
    {
      sets: [
        {
          amount: 75,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 95,
          description: "Peak set",
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 1,
          repsIsMinimum: true,
        },
        {
          amount: 90,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 80,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 65,
          description: null,
          movementIndex: 3,
          percentageOfMaxIndex: 3,
          reps: 3,
          repsIsMinimum: true,
        },
        {
          amount: 50,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 1,
          percentageOfMaxIndex: 1,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 0,
          description: "Back, Abs",
          movementIndex: 6,
          percentageOfMaxIndex: null,
          reps: null,
          repsIsMinimum: false,
        },
      ],
    },
    {
      sets: [
        {
          amount: 75,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 95,
          description: "Peak set",
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 1,
          repsIsMinimum: true,
        },
        {
          amount: 90,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 85,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 80,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 75,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 70,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 65,
          description: null,
          movementIndex: 0,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: true,
        },
        {
          amount: 40,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 50,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 3,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 5,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 7,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 4,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 6,
          repsIsMinimum: false,
        },
        {
          amount: 60,
          description: null,
          movementIndex: 5,
          percentageOfMaxIndex: 0,
          reps: 8,
          repsIsMinimum: false,
        },
        {
          amount: 0,
          description: "Arms, Other",
          movementIndex: 6,
          percentageOfMaxIndex: null,
          reps: null,
          repsIsMinimum: false,
        },
      ],
    },
    {
      sets: [],
    },
  ],
  movements: [
    {
      type: "new",
      name: "Bench Press",
      description: null,
    },
    {
      type: "new",
      name: "Squat",
      description: null,
    },
    {
      type: "new",
      name: "Overhead Press",
      description: null,
    },
    {
      type: "new",
      name: "Deadlift",
      description: null,
    },
    {
      type: "new",
      name: "Sumo Deadlift",
      description: null,
    },
    {
      type: "new",
      name: "Close-Grip Bench",
      description: null,
    },
    {
      type: "new",
      name: "Accessories",
      description: null,
    },
  ],
} satisfies NewProgramTemplate